// <auto-generated />
namespace ira.MigrationsApplicationContext
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class RoleID : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RoleID));
        
        string IMigrationMetadata.Id
        {
            get { return "201511020437524_RoleID"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
