// <auto-generated />
namespace ira.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class firstnamelastname : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(firstnamelastname));
        
        string IMigrationMetadata.Id
        {
            get { return "201507070352290_firstnamelastname"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
