// <auto-generated />
namespace ira.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class nullablees1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(nullablees1));
        
        string IMigrationMetadata.Id
        {
            get { return "201507130131009_nullablees1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
