// <auto-generated />
namespace ira.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class updatetable15061501 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatetable15061501));
        
        string IMigrationMetadata.Id
        {
            get { return "201506150157366_updatetable150615-01"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
