// <auto-generated />
namespace ira.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class multilinemsg : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(multilinemsg));
        
        string IMigrationMetadata.Id
        {
            get { return "201505271016037_multilinemsg"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
