// <auto-generated />
namespace ira.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class ikhtisar1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ikhtisar1));
        
        string IMigrationMetadata.Id
        {
            get { return "201511300312430_ikhtisar1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
