// <auto-generated />
namespace ira.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class uraianunitpendek : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(uraianunitpendek));
        
        string IMigrationMetadata.Id
        {
            get { return "201601060639327_uraianunitpendek"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
