//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ira.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_ira_st
    {
        public string nost { get; set; }
        public Nullable<System.DateTime> tglst { get; set; }
        public string halst { get; set; }
        public Nullable<int> tahunst { get; set; }
    }
}
