//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ira.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_ira_tpu
    {
        public int TpuID { get; set; }
        public string NamaTpu { get; set; }
        public int JenisTpuID { get; set; }
        public int UnitID { get; set; }
        public int TahunAnggaran { get; set; }
    }
}
