//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ira.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ViewTPUEntities : DbContext
    {
        public ViewTPUEntities()
            : base("name=ViewTPUEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<v_ira_jenistpu_pkpt> v_ira_jenistpu_pkpt { get; set; }
        public virtual DbSet<v_ira_tpu> v_ira_tpu { get; set; }
        public virtual DbSet<v_ira_unit_pkpt> v_ira_unit_pkpt { get; set; }
    }
}
